/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MuhammedAbdullah
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public GameFrame() {
        initComponents();
        path = this.getClass().getProtectionDomain().getCodeSource().getLocation().toString();
        path = path.substring(6, path.length());
        firstPath = path + "src/as.png";
        crossPath = path + "src/1x.png";
        ovalPath = path + "src/rc.png";
        this.pack();
        this.setLocationRelativeTo(null);
    }

    String path;
    String firstPath;
    String crossPath;
    String ovalPath;
    public static int state = 0;
    public static boolean flag = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 110, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 70, 110, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 70, 110, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 110, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 180, 110, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 180, 110, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 290, 110, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 290, 110, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/as.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 290, 110, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.out.println("0,0");
        if (Main.userMove(0, 0)) {
            jLabel1.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.out.println("0,1");
        if (Main.userMove(0, 1)) {
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        if (Main.userMove(0, 2)) {
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        if (Main.userMove(1, 0)) {
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        if (Main.userMove(1, 1)) {
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        if (Main.userMove(1, 2)) {
            jLabel6.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        if (Main.userMove(2, 0)) {
            jLabel7.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        if (Main.userMove(2, 1)) {
            jLabel8.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        if (Main.userMove(2, 2)) {
            jLabel9.setIcon(new ImageIcon(getClass().getResource("/src/1x.png")));
            controlState(state);
            Main.robot();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    public void play1() {
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play2() {
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play3() {
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play4() {
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play5() {
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play6() {
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play7() {
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play8() {
        jLabel8.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void play9() {
        jLabel9.setIcon(new ImageIcon(getClass().getResource("/src/rc.png")));
        controlState(state);
    }

    public void controlState(int state) {
        int dialogButton, dialogResult;
        if (state == 1) {
            dialogButton = JOptionPane.YES_NO_OPTION;
            dialogResult = JOptionPane.showConfirmDialog(this, "You lost. Would you like to restart game?", "End Of Game", dialogButton);
            if (dialogResult == 0) {
                Main.gameSpace = new int[3][3];
                Main.state = 0;
                state = 0;
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel2.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel4.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel5.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel6.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel7.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel8.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel9.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));

                flag = false;
            } else {
                System.exit(0);
            }
        } else if (state == 2) {
            dialogButton = JOptionPane.YES_NO_OPTION;
            dialogResult = JOptionPane.showConfirmDialog(this, "You won. Would you like to restart game?", "Congratulations!", dialogButton);
            if (dialogResult == 0) {
                Main.gameSpace = new int[3][3];
                Main.state = 0;
                state = 0;
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel2.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel4.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel5.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel6.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel7.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel8.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                jLabel9.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));

                flag = false;
            } else {
                System.exit(0);
            }
        } else {
            if (Main.isCompleted()) {
                dialogButton = JOptionPane.YES_NO_OPTION;
                dialogResult = JOptionPane.showConfirmDialog(this, "Would you like to restart game?", "Scoreless!", dialogButton);
                if (dialogResult == 0) {
                    Main.gameSpace = new int[3][3];
                    Main.state = 0;
                    state = 0;
                    jLabel1.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel3.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel4.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel5.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel6.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel7.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel8.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));
                    jLabel9.setIcon(new ImageIcon(getClass().getResource("/src/as.png")));

                    flag = false;
                } else {
                    System.exit(0);
                }
            } else {
                flag = true;
            }
        }

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
